# Generated by Django 5.1.1 on 2024-10-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccination',
            old_name='campaignn',
            new_name='campaign',
        ),
        migrations.RemoveField(
            model_name='vaccination',
            name='updtaed_on',
        ),
        migrations.AddField(
            model_name='vaccination',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
